const ActionType = {
    REQ_GET_BOOTCAMP : 'REQ_GET_BOOTCAMP',
    RES_GET_BOOTCAMP : 'RES_GET_BOOTCAMP',
    REQ_GET_BOOTCAMP_BY_ID : 'REQ_GET_BOOTCAMP_BY_ID',
    RES_GET_BOOTCAMP_BY_ID : 'RES_GET_BOOTCAMP_BY_ID',

    //getProgName
    REQ_GET_PROGNAME : 'REQ_GET_PROGNAME',
    RES_GET_PROGNAME : 'RES_GET_PROGNAME'
}

export default ActionType